<a href="https://colab.research.google.com/github/Iannoh-png/AI-Final-Project-G16/blob/main/Copy_of_Group_7_Practical_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = pd.read_csv("sales_data_dirty.csv")

print(data.head())
print(data.info())

   OrderID  CustomerName       Product     Category Quantity  Price  \
0     1001    John Kamau        Laptop  Electronics        2  75000
1     1002  Mary Wanjiku         Mouse  Electronics        5   1500
2     1003  Peter Otieno      Keyboard  Electronics      NaN   2500
3     1004  Amina Hassan  Office Chair    Furniture        1  12000
4     1005  David Mwangi          Desk    Furniture      Two  30000

    OrderDate   Region PaymentMethod
0  05/01/2025  Nairobi         Mpesa
1  05/01/2025   Nakuru        M-Pesa
2  06/01/2025   Kisumu          Cash
3  07/01/2025  Mombasa          Card
4  08/01/2025  Nairobi         Mpesa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        20 non-null     int64
 1   CustomerName   19 non-null     object
 2   Product        20 non-null     object
 3   Category       20 non-null     object
 4   Quantity       19 non-null     object
 5   Price          19 non-null     object
 6   OrderDate      19 non-null     object
 7   Region         19 non-null     object
 8   PaymentMethod  20 non-null     object
dtypes: int64(1), object(8)
memory usage: 1.5+ KB
None

In [ ]:
data.describe()

          OrderID
count    20.00000
mean   1010.50000
std       5.91608
min    1001.00000
25%    1005.75000
50%    1010.50000
75%    1015.25000
max    1020.00000

In [ ]:
data.isnull().sum()

OrderID          0
CustomerName     1
Product          0
Category         0
Quantity         1
Price            1
OrderDate        1
Region           1
PaymentMethod    0
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.duplicated(subset=['CustomerName', 'Product', 'Category', 'Quantity', 'Price', 'OrderDate', 'Region', 'PaymentMethod']).sum()

np.int64(1)

In [ ]:
print(data.isnull().sum())

OrderID          0
CustomerName     1
Product          0
Category         0
Quantity         1
Price            1
OrderDate        1
Region           1
PaymentMethod    0
dtype: int64

In [ ]:
print(data[data.isnull().any(axis=1)])

    OrderID   CustomerName   Product     Category Quantity  Price   OrderDate  \
2      1003   Peter Otieno  Keyboard  Electronics      NaN   2500  06/01/2025
7      1008            NaN   Printer  Electronics        1  15000  10/01/2025
13     1014   Linda Akinyi   Monitor  Electronics        1    NaN  13/01/2025
15     1016  Susan Wairimu      Desk    Furniture        1  30000         NaN
17     1018  Joseph Mwangi    Laptop  Electronics        1  71000  15/01/2025

     Region PaymentMethod
2    Kisumu          Cash
7   Nairobi         Mpesa
13   Kisumu         Mpesa
15  Nairobi         Mpesa
17      NaN          Card

In [ ]:
print(data['Category'].unique())

['Electronics' 'Furniture' 'Furn.' 'electronic']

In [ ]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        20 non-null     int64
 1   CustomerName   19 non-null     object
 2   Product        20 non-null     object
 3   Category       20 non-null     object
 4   Quantity       19 non-null     object
 5   Price          19 non-null     object
 6   OrderDate      19 non-null     object
 7   Region         19 non-null     object
 8   PaymentMethod  20 non-null     object
dtypes: int64(1), object(8)
memory usage: 1.5+ KB
None

In [ ]:
# Running Quantity column which should be a whole number but is stored as object
print(data['Quantity'].unique())

['2' '5' nan '1' 'Two' '3' '4' '-1' 'four']

In [ ]:
#Price Column should be numeric but stored as Object
print(data['Price'].unique())

['75000' '1500' '2500' '12000' '30000' 'KES 70000' '18000' '15000' '28000'
 '1400' '72000' nan '71000']

In [ ]:
cols = [c for c in data.columns if c != 'OrderID']
print(data.duplicated(subset=cols).sum())

1

In [ ]:
cols = [c for c in data.columns if c != 'OrderID']
print(data[data.duplicated(subset=cols, keep=False)])

    OrderID CustomerName Product     Category Quantity  Price   OrderDate  \
0      1001   John Kamau  Laptop  Electronics        2  75000  05/01/2025
12     1013   John Kamau  Laptop  Electronics        2  75000  05/01/2025

     Region PaymentMethod
0   Nairobi         Mpesa
12  Nairobi         Mpesa

In [ ]:
# Convert Quantity to numeric first (ignoring text errors)
data['Quantity_numeric'] = pd.to_numeric(data['Quantity'], errors='coerce')

# Find Negative quantities
print(data[data['Quantity_numeric'] < 0])

    OrderID    CustomerName       Product   Category Quantity  Price  \
14     1015  Brian Odhiambo  Office Chair  Furniture       -1  12000

     OrderDate   Region PaymentMethod  Quantity_numeric
14  14/01/2025  Mombasa          Card              -1.0

In [ ]:
# Try to convert dates and find ones that fail
data['OrderDate_converted'] = pd.to_datetime(data['OrderDate'], errors='coerce')

# Show rows where date conversion failed
print(data[data['OrderDate_converted'].isna()])

    OrderID    CustomerName       Product     Category Quantity  Price  \
13     1014    Linda Akinyi       Monitor  Electronics        1    NaN
14     1015  Brian Odhiambo  Office Chair    Furniture       -1  12000
15     1016   Susan Wairimu          Desk    Furniture        1  30000
16     1017   Kevin Kiprono       Printer  Electronics        3  15000
17     1018   Joseph Mwangi        Laptop  Electronics        1  71000
18     1019   Emily Naliaka         Mouse  Electronics     four   1500

     OrderDate   Region PaymentMethod  Quantity_numeric OrderDate_converted
13  13/01/2025   Kisumu         Mpesa               1.0                 NaT
14  14/01/2025  Mombasa          Card              -1.0                 NaT
15         NaN  Nairobi         Mpesa               1.0                 NaT
16  2025-13-01   Nakuru         Mpesa               3.0                 NaT
17  15/01/2025      NaN          Card               1.0                 NaT
18  16/01/2025  Eldoret         Mpesa               NaN                 NaT

In [ ]:
print(data[data['Region'].isnull()])

    OrderID   CustomerName Product     Category Quantity  Price   OrderDate  \
17     1018  Joseph Mwangi  Laptop  Electronics        1  71000  15/01/2025

   Region PaymentMethod  Quantity_numeric OrderDate_converted
17    NaN          Card               1.0                 NaT